import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawn } from 'node:child_process';

const cli=resolve('agents/skills/local-issue-tracker/local-issue-tracker.mjs');
async function repo(){const root=await mkdtemp(join(tmpdir(),'tracker-graph-'));await mkdir(join(root,'.git'));return root}
function run(args,cwd){return new Promise(done=>{const p=spawn(process.execPath,[cli,...args],{cwd});let stdout='',stderr='';p.stdout.on('data',d=>stdout+=d);p.stderr.on('data',d=>stderr+=d);p.on('close',status=>done({status,stdout,stderr}));p.stdin.end()})}
async function create(root,title,triage='ready-for-agent'){const r=await run(['create','demo','--title',title,'--triage',triage,'--json'],root);assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout)}
async function resolveIssue(root,issue){await run(['claim',issue.identity],root);const p=join(root,issue.path);await writeFile(p,(await readFile(p,'utf8'))+'\n## Answer\n\nDone.\n');const r=await run(['resolve',issue.identity],root);assert.equal(r.status,0,r.stderr)}

test('block and unblock preserve bytes, sort blockers, and consistently reject duplicates',async()=>{const root=await repo(),a=await create(root,'A'),b=await create(root,'B'),target=await create(root,'Target');const path=join(root,target.path),original=await readFile(path,'utf8');let r=await run(['block',target.identity,b.identity,'--json'],root);assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),target);r=await run(['block',target.identity,a.identity],root);assert.equal(r.status,0,r.stderr);const changed=await readFile(path,'utf8');assert.equal(changed,original.replace('Blocked by: None','Blocked by: 01, 02'));for(const json of [false,true]){r=await run(['block',target.identity,a.identity,...(json?['--json']:[])],root);assert.notEqual(r.status,0);assert.equal(await readFile(path,'utf8'),changed)}r=await run(['unblock',target.identity,a.identity],root);assert.equal(r.status,0,r.stderr);assert.equal(await readFile(path,'utf8'),original.replace('Blocked by: None','Blocked by: 02'))});

test('block rejects missing, cross-effort, self, cycles, and non-open targets without mutation',async()=>{const root=await repo(),a=await create(root,'A'),b=await create(root,'B');const other=(await run(['create','other','--title','Other','--json'],root));assert.equal(other.status,0);for(const args of [['block',a.identity,'demo/99'],['block',a.identity,JSON.parse(other.stdout).identity],['block',a.identity,a.identity]]){const before=await readFile(join(root,a.path),'utf8'),r=await run(args,root);assert.notEqual(r.status,0);assert.equal(await readFile(join(root,a.path),'utf8'),before)}assert.equal((await run(['block',a.identity,b.identity],root)).status,0);let r=await run(['block',b.identity,a.identity],root);assert.notEqual(r.status,0);await run(['claim',b.identity],root);r=await run(['unblock',b.identity,a.identity],root);assert.notEqual(r.status,0)});

test('frontier defaults to every triage role and supports canonical triage filters',async()=>{const root=await repo(),done=await create(root,'Done'),blocked=await create(root,'Blocked'),agent=await create(root,'Agent'),human=await create(root,'Human','ready-for-human'),triage=await create(root,'Triage','needs-triage'),info=await create(root,'Info','needs-info'),declined=await create(root,'Declined','wontfix'),claimed=await create(root,'Claimed'),stillBlocked=await create(root,'Still blocked');await run(['block',blocked.identity,done.identity],root);await run(['block',stillBlocked.identity,claimed.identity],root);await run(['claim',claimed.identity],root);await resolveIssue(root,done);let r=await run(['frontier','demo','--json'],root);assert.equal(r.status,0,r.stderr);let data=JSON.parse(r.stdout);assert.equal(data.effort,'demo');assert.deepEqual(data.issues.map(x=>x.identity),['demo/02','demo/03','demo/04','demo/05','demo/06','demo/07']);assert.deepEqual(Object.keys(data.issues[0]),['identity','path','triage','state','blockers']);assert.deepEqual(data.issues[0].blockers,[1]);for(const role of ['needs-triage','needs-info','ready-for-agent','ready-for-human','wontfix']){r=await run(['frontier','demo','--triage',role,'--json'],root);assert.equal(r.status,0,r.stderr);assert.ok(JSON.parse(r.stdout).issues.every(issue=>issue.triage===role))}r=await run(['frontier','demo','--triage','ready-for-agent'],root);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/demo\/02/);assert.match(r.stdout,/demo\/03/);assert.ok(r.stdout.indexOf('demo/02')<r.stdout.indexOf('demo/03'));for(const issue of [human,triage,info,declined,claimed,done,stillBlocked])assert.doesNotMatch(r.stdout,new RegExp(issue.identity.replace('/','\\/')));r=await run(['frontier','demo','--triage','not-a-role'],root);assert.equal(r.status,1);assert.equal(r.stdout,'');assert.match(r.stderr,/local-issue-tracker: unsupported triage role/)});

test('frontier preserves empty human and JSON output shapes',async()=>{const root=await repo();await create(root,'Human','ready-for-human');let r=await run(['frontier','demo','--triage','ready-for-agent','--json'],root);assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),{effort:'demo',issues:[]});r=await run(['frontier','demo','--triage','ready-for-agent'],root);assert.equal(r.status,0,r.stderr);assert.equal(r.stdout,'No agent-ready issues in demo\n')});

test('claim rechecks blockers after acquiring the effort lock',async()=>{const root=await repo(),blocker=await create(root,'Blocker'),target=await create(root,'Target');const lock=join(root,'.scratch/demo/.local-issue-tracker.lock');await mkdir(lock);const pending=run(['claim',target.identity],root);await new Promise(r=>setTimeout(r,100));const path=join(root,target.path),text=await readFile(path,'utf8');await writeFile(path,text.replace('Blocked by: None','Blocked by: 01'));await rm(lock,{recursive:true});const result=await pending;assert.notEqual(result.status,0);assert.match(result.stderr,/blocked/);assert.match(await readFile(path,'utf8'),/State: open/);void blocker});
