import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawn } from 'node:child_process';

const cli=resolve('agents/skills/local-issue-tracker/local-issue-tracker.mjs');
async function repo(){const root=await mkdtemp(join(tmpdir(),'tracker-life-'));await mkdir(join(root,'.git'));return root}
function run(args,cwd){return new Promise(done=>{const p=spawn(process.execPath,[cli,...args],{cwd});let stdout='',stderr='';p.stdout.on('data',d=>stdout+=d);p.stderr.on('data',d=>stderr+=d);p.on('close',status=>done({status,stdout,stderr}));p.stdin.end()})}
async function create(root,title,triage='needs-triage',extra=[]){const r=await run(['create','demo','--title',title,'--triage',triage,'--json',...extra],root);assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout)}
async function unchanged(root,path,args){const before=await readFile(join(root,path),'utf8');const r=await run(args,root);assert.notEqual(r.status,0);assert.equal(await readFile(join(root,path),'utf8'),before);return r}

test('set-triage changes only canonical triage on open issues and reports identity',async()=>{const root=await repo(),issue=await create(root,'Triage');const path=join(root,issue.path),before=await readFile(path,'utf8');let r=await run(['set-triage','demo/01','ready-for-human','--json'],root);assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),issue);assert.equal(await readFile(path,'utf8'),before.replace('Triage: needs-triage','Triage: ready-for-human'));await unchanged(root,issue.path,['set-triage','demo/01','invalid']);await run(['claim','demo/01'],root);await unchanged(root,issue.path,['set-triage','demo/01','needs-info'])});

test('claim requires open, unblocked, actionable canonical issue and concurrent claims have one winner',async()=>{const root=await repo();for(const role of ['needs-triage','needs-info','wontfix']){const i=await create(root,role,role);await unchanged(root,i.path,['claim',i.identity])}const blocker=await create(root,'Blocker','ready-for-agent'),blocked=await create(root,'Blocked','ready-for-agent',['--blocked-by','1']);await unchanged(root,blocked.path,['claim',blocked.identity]);let races=await Promise.all([run(['claim',blocker.identity,'--json'],root),run(['claim',blocker.identity,'--json'],root)]);assert.equal(races.filter(x=>x.status===0).length,1);assert.equal(races.filter(x=>x.status!==0).length,1);const text=await readFile(join(root,blocker.path),'utf8');assert.match(text,/State: claimed/);assert.doesNotMatch(text,/Claimant|Assignee|Timestamp|Lease/i)});

test('release only accepts claimed issues and preserves all prose bytes',async()=>{const root=await repo(),issue=await create(root,'Release','ready-for-agent',['--body','Body  bytes\n\n## Notes\nExact']);await unchanged(root,issue.path,['release',issue.identity]);await run(['claim',issue.identity],root);const claimed=await readFile(join(root,issue.path),'utf8');const r=await run(['release',issue.identity,'--json'],root);assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),issue);assert.equal(await readFile(join(root,issue.path),'utf8'),claimed.replace('State: claimed','State: open'))});

test('resolution requires non-empty Answer and permits open resolution only for wontfix',async()=>{const root=await repo(),normal=await create(root,'Normal','ready-for-agent');await run(['claim',normal.identity],root);await unchanged(root,normal.path,['resolve',normal.identity]);await writeFile(join(root,normal.path),(await readFile(join(root,normal.path),'utf8'))+'\n## Answer\n\nDone.\n');let r=await run(['resolve',normal.identity,'--json'],root);assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),normal);await unchanged(root,normal.path,['release',normal.identity]);await unchanged(root,normal.path,['set-triage',normal.identity,'needs-info']);await unchanged(root,normal.path,['resolve',normal.identity]);const noClaim=await create(root,'No claim','ready-for-human',['--body','## Answer\n\nDone']);await unchanged(root,noClaim.path,['resolve',noClaim.identity]);const empty=await create(root,'Empty decline','wontfix',['--body','## Answer\n\n   \n## Notes\nNope']);await unchanged(root,empty.path,['resolve',empty.identity]);const decline=await create(root,'Decline','wontfix',['--body','Intro\n\n## Answer\n\nRationale.\n']);r=await run(['resolve',decline.identity],root);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/Resolved demo\/04/)});

test('legacy issues reject lifecycle mutations without changing files and reopen is not exposed',async()=>{const root=await repo(),dir=join(root,'.scratch/demo/issues');await mkdir(dir,{recursive:true});const path=join(dir,'01-legacy.md'),text='# Legacy\n\nStatus: ready-for-agent\n\nBody\n';await writeFile(path,text);for(const command of [['claim','demo/01'],['release','demo/01'],['resolve','demo/01'],['set-triage','demo/01','wontfix'],['reopen','demo/01']]){const r=await run(command,root);assert.notEqual(r.status,0);assert.equal(await readFile(path,'utf8'),text)}});
