import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawn } from 'node:child_process';

const cli=resolve('agents/skills/local-issue-tracker/local-issue-tracker.mjs');
async function repo(){const root=await mkdtemp(join(tmpdir(),'tracker-migrate-'));await mkdir(join(root,'.git'));return root}
function run(args,cwd){return new Promise(done=>{const p=spawn(process.execPath,[cli,...args],{cwd});let stdout='',stderr='';p.stdout.on('data',d=>stdout+=d);p.stderr.on('data',d=>stderr+=d);p.on('close',status=>done({status,stdout,stderr}));p.stdin.end()})}
async function put(root,effort,name,text){const dir=join(root,'.scratch',effort,'issues');await mkdir(dir,{recursive:true});await writeFile(join(dir,name),text);return join(dir,name)}

test('reads report legacy status as noncanonical and mutations give migration guidance',async()=>{const root=await repo(),path=await put(root,'demo','01-old.md','# Old\n\nStatus: ready-for-agent\n\nBody\n');let r=await run(['show','demo/01','--json'],root);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).canonical,false);r=await run(['list','demo'],root);assert.match(r.stdout,/noncanonical/i);r=await run(['validate','demo','--json'],root);assert.equal(r.status,2);assert.ok(JSON.parse(r.stdout).findings.some(x=>x.code==='legacy-metadata'));const before=await readFile(path,'utf8');r=await run(['claim','demo/01'],root);assert.notEqual(r.status,0);assert.match(r.stderr,/migrate demo/);assert.equal(await readFile(path,'utf8'),before)});

test('migrates every legacy status category and preserves title and prose bytes',async()=>{const root=await repo();const prose='## Work\n\nKeep  spaces.\n\n';for(const [n,status] of [[1,'needs-info'],[2,'ready-for-human'],[3,'claimed'],[4,'resolved']])await put(root,'demo',`${String(n).padStart(2,'0')}-x.md`,`# Title ${n}\n\nStatus: ${status}\nType: task\nBlocked by: None\n\n${prose}${status==='resolved'?'## Answer\n\ndone\n':''}`);await put(root,'demo','05-missing.md',`# Missing\n\nType: prototype\nBlocked by: None\n\n${prose}`);const r=await run(['migrate','demo','--triage','ready-for-agent','--json'],root);assert.equal(r.status,0,r.stderr);const out=JSON.parse(r.stdout);assert.equal(out.issues.filter(x=>x.status==='converted').length,5);for(let n=1;n<=5;n++){const text=await readFile(join(root,'.scratch/demo/issues',`${String(n).padStart(2,'0')}-${n===5?'missing':'x'}.md`),'utf8');assert.match(text,/Issue metadata: manage/);assert.ok(text.includes(prose));assert.match(text,/Triage: (needs-info|ready-for-human|ready-for-agent)/)}assert.match(await readFile(join(root,'.scratch/demo/issues/03-x.md'),'utf8'),/State: claimed/);assert.match(await readFile(join(root,'.scratch/demo/issues/04-x.md'),'utf8'),/State: resolved/)});

test('ambiguous triage, malformed relationships, and graph failure roll back the whole effort',async()=>{for(const bad of ['# Missing\n\nBody\n','# Bad\n\nStatus: ready-for-agent\nBlocked by: ../02\n\nBody\n']){const root=await repo(),a=await put(root,'demo','01-good.md','# Good\n\nStatus: ready-for-agent\n\nBody\n'),b=await put(root,'demo','02-bad.md',bad),beforeA=await readFile(a,'utf8'),beforeB=await readFile(b,'utf8');const r=await run(['migrate','demo','--json'],root);assert.notEqual(r.status,0);assert.equal(await readFile(a,'utf8'),beforeA);assert.equal(await readFile(b,'utf8'),beforeB)}const root=await repo(),a=await put(root,'demo','01-a.md','# A\n\nStatus: ready-for-agent\nBlocked by: 02\n\nA\n'),b=await put(root,'demo','02-b.md','# B\n\nStatus: ready-for-agent\nBlocked by: 01\n\nB\n');const before=[await readFile(a,'utf8'),await readFile(b,'utf8')];const r=await run(['migrate','demo'],root);assert.notEqual(r.status,0);assert.deepEqual([await readFile(a,'utf8'),await readFile(b,'utf8')],before)});

test('repository migration is explicit and reports converted, canonical, and failed efforts stably',async()=>{const root=await repo();await put(root,'a','01-old.md','# Old\n\nStatus: ready-for-agent\n\nBody\n');await put(root,'b','01-new.md','# New\n\n<!-- Issue metadata: manage with the local-issue-tracker skill. -->\nTriage: needs-triage\nState: open\nBlocked by: None\n\nBody\n');await put(root,'c','01-bad.md','# Bad\n\nStatus: claimed\n\nBody\n');let r=await run(['migrate','--json'],root);assert.notEqual(r.status,0);assert.match(r.stderr,/effort.*required/i);r=await run(['migrate','--repository','--json'],root);assert.notEqual(r.status,0);const out=JSON.parse(r.stdout);assert.deepEqual(out.efforts.map(x=>[x.effort,x.status]),[['a','converted'],['b','already-canonical'],['c','failed']]);assert.match(await readFile(join(root,'.scratch/a/issues/01-old.md'),'utf8'),/Triage: ready-for-agent/);assert.match(await readFile(join(root,'.scratch/c/issues/01-bad.md'),'utf8'),/Status: claimed/)});
